include:
  - board: xiao_ble
    shield: totem_left
#    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_dongle_left
  - board: xiao_ble
    shield: totem_right
#    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_dongle_right
  - board: xiao_ble
    shield: totem_dongle prospector_adapter
    artifact-name: dongle-screen
  - board: xiao_ble
    shield: settings_reset
    artifact-name: totem-settings-reset

# seeeduino_xiao_ble
