include:
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_dongle_left
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_dongle_right
  - board: xiao_ble//zmk
    shield: totem_dongle prospector_adapter
    artifact-name: dongle-screen
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: totem-settings-reset

# seeeduino_xiao_ble
