include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact-name: totem_dongle_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem_dongle_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact-name: dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: totem-settings-reset
